[package]
name = "filesearch-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "filesearch_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tokio = { version = "1", features = ["net", "time"] }
